#!/bin/sh
# stash unstaged changes, run release task, stage release updates and restore stashed files

PATH=$PATH:/usr/local/bin:/usr/local/sbin

NAME=$(git branch | grep '*' | sed 's/* //')

# don't run on rebase
if [ $NAME != '(no branch)' ]
then
 git stash -q --keep-index
  grunt release

  RETVAL=$?

  if [ $RETVAL -ne 0 ]
  then
    exit 1
  fi

  git add .
  git stash pop -q
fi